### ISSUE TITLE
URL error during running Trial run (1 small news outlet)

### ISSUE THREAD

**Issue by aviclu** [UKPLab/emnlp2021-hypercoref-cdcr#1]
I was trying to run the `run_pipeline.py` python script as stated in the README file, under the `hypercoref-pipeline` container, but got the following error for every URL line:

> Message: 'Could not obtain https://www.wired.com/story/youtube-police-political-videos-more-closely/ from https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2020-10/segments/1581875141806.26/warc/CC-MAIN-20200217085334-20200217115334-00324.warc.gz.'
> Arguments: (ArchiveLoadFailed('Unknown archive format, first line: [\'<?xml\', \'version="1.0"\', \'encoding="UTF-8"?>\']'),)

And finally, the script yielded the error message:

> KeyError: "None of ['url-normalized'] are in the columns"

This ended without creating the `7_CreateSplitsStage_create_splits` (but only `1_...`, `3_...,` and `6_...`).

Here is the full event log:

> MainThread - 2022-05-15 07:30:38,039 - INFO - pipeline_runner - Creating pipeline for config 'article_extraction_wired.com'...
> MainThread - 2022-05-15 07:30:38,190 - INFO - warc_extraction - Using newspaper3k for cleaning markup.
> MainThread - 2022-05-15 07:30:38,367 - INFO - create_splits - Using kahypar hypergraph partitioning for creating splits.
> MainThread - 2022-05-15 07:30:38,367 - INFO - pipeline_runner - Pipeline created: 00__DummyFeederStage --> 01__WarcExtractionStage --> 02__PostProcessPageContentStage --> 03__HyperlinksPostProcessingStage --> 04__AnchorsIntoOneFileStage --> 05__ClusterAnalysisStage --> 06__TokenizeStage --> 07__CreateSplitsStage --> 08__CleanupStage
> MainThread - 2022-05-15 07:30:38,367 - INFO - pipeline_runner - Starting pipeline.
> MainThread - 2022-05-15 07:30:38,367 - INFO - pipeline_runner - Running python.pipeline.common.dummy_feeder_stage.DummyFeederStage
> MainThread - 2022-05-15 07:30:38,368 - INFO - pipeline_runner - Running python.data.pipeline.warc_extraction.warc_extraction.WarcExtractionStage
> MainThread - 2022-05-15 07:30:38,917 - INFO - warc_extraction - Downloading and cleaning approximately 13245 pages...
> MainThread - 2022-05-15 07:32:46,958 - INFO - warc_extraction - Done.
> MainThread - 2022-05-15 07:32:46,962 - DEBUG - warc_extraction - Pages will now be indexed by their normalized URL.

**Comment by mbugert** [comment]
@aviclu Thanks for reporting. The problem appears to be that CC [has changed the URL prefix for public access in April this year](https://commoncrawl.org/2022/03/introducing-cloudfront-access-to-common-crawl-data/).

As a quick fix, run the following inside the docker container after the `docker_get_seed_data.sh` step:
```bash
find /hypercoref/working_dir/page_seeding -name "*.csv" -exec sed -i 's/https:\/\/commoncrawl.s3.amazonaws.com\//https:\/\/data.commoncrawl.org\//g' {} \;
```
The pipeline should run properly then. :blush: 

I'll keep this issue open until I have integrated a fix either in the source files or in the `sh` script.

**Comment by mbugert** [comment]
- The seed URLs for recreating the corpus are fixed.
- The code is fixed, so that future data creation efforts from scratch will use a working URL prefix.
- Docker image is updated.
